### ISSUE TITLE
ASMA: unsupported (non-extended?) jump mnemonics

### ISSUE THREAD

**Issue by Fish-Git** [s390guy/SATK#10]
I am currently using: &nbsp;<b>(*)</b>

&nbsp; &nbsp; &nbsp; **Revision: 7565b3e8ac73858f80f55e7068772558e89d70d9**
&nbsp; &nbsp; &nbsp; Date: **3/24/2017** 11:07:51 AM
&nbsp; &nbsp; &nbsp; Message: **Fix font inconsistency in macro doc headings in func.odt and func.pdf**

I've started trying to use jump mnemonics and relative and immediate instructions as much as possible (to eliminate the need for a base register) but occasionally run into trouble such as the following:

```
00002310                                           277 ABORT    DS    0H
                                                   278          JC    B'0100',FAILURE  CC1: indeterminate (unexpected)
          ** [278] @[278]-1 macro definition for JC not found in MACLIB path as JC.mac
                                                   279          JC    B'0001',FAILURE  CC3: persistent (unexpected)
          ** [279] @[279]-1 macro definition for JC not found in MACLIB path as JC.mac
                                                   280 *                               CC2: transient (retry up to 6 times)
```

The `JE`, `JNE`, `JL`, `JH`, etc, mnemonics work fine (at least I _think_ they do! I can't remember right now), but apparently the plain non-extended jump mnemonic(s) is (aren't) supported.

It would be nice if they were. &nbsp; `:)`
___
<b>(*)</b>&nbsp; _See issue #9 for the reason why._

**Comment by s390guy** [comment]
They are.  The non-extended version of these instructions is BRC not JC.  Try BRC and report any problems.  It is defined to ASMA.

**Comment by Fish-Git** [comment]
> The non-extended version of these instructions is BRC not JC.

(Oops!) You're right. My bad. You can delete this _completely bogus_ github issue if you want.

In the mean time I'm going to go ahead and close it.

Sorry to bother you!
