### ISSUE TITLE
No PUSH/POP USING

### ISSUE THREAD

**Issue by s390guy** [s390guy/SATK#13]
PUSH/POP USING is missing.  On the list of things to do.

**Comment by s390guy** [comment]
ASMA has been enhanced with support for PUSH USING and POP USING.  The ASMA.odt and ASMA.pdf documents have been updated to reflect this.  The PUSH and POP directives operate as expected.

I will leave this open until I have received some user feed back on this enhancement

**Comment by Fish-Git** [comment]
Thank you, Harold!

While I personally don't recall ever needing such a feature in any of my ASMA projects (I _may_ have, I just can't remember off the top of my head!), I _do_ very much appreciate your adding such functionality.

I don't have time to test it right now, but whenever I get the chance I will do so and try to remember to report back here with my experience.

Thanks again for all of your hard work with SATK/ASMA! It's a fantastic product!

_(And yes, I haven't forgotten about my promise to try and document for you how I myself use it on Windows either! Finding those "Round Tuits" is becoming harder and harder as time goes by it seems! But I promise you I will get around to it eventually!)_

**Comment by Fish-Git** [comment]
(Oops!) I never got around to testing that for you, did I? Sorry about that! &nbsp; `:(`

Nevertheless, I'm pretty confident it's probably working absolutely correctly. &nbsp; `:)`

**Comment by s390guy** [comment]
No problem.  It works as I think it should based on the limited info in the HLASM doc.  So, seeing if it works as someone else thinks it should would be valuable.  And, not important at all, it works as how I've used it.  Whenever you get to it, or someone else is fine.
