### ISSUE TITLE
Bug in -v/--vmc option: incorrect output format/syntax

### ISSUE THREAD

**Issue by Fish-Git** [s390guy/SATK#16]
FYI: after giving the `-v`/`--vmc` option a try, I noticed the resulting output file looked like the following:

```
CP STORE R S 0 0008000000000200
CP STORE R S 68 00080000000005A8
CP STORE R S 8C 00000000
CP STORE R S 200 B2020618B7010630BF11065E58200638
CP STORE R S 210 0812BF11065F5820063C0812BF110660
CP STORE R S 220 582006400812582006380912BD11065E
CP STORE R S 230 477002315820063C0912BD11065F4770
...etc...
```

Unfortunately however, CP kicks out each and every statement with a syntax error, due to the following note appearing at the beginning of the [CP STORE command's Help information](https://www.ibm.com/docs/en/zvm/7.1?topic=commands-store-guest-storage-zarchitecture):

> _"Note:  Do not put blanks between the operands and the address specified by hexloc. However, at least one blank must precede the data you want to put into storage."_

So the _proper_ output file format should actually be:

```
CP STORE RS0 0008000000000200
CP STORE RS68 00080000000005A8
CP STORE RS8C 00000000
CP STORE RS200 B2020618B7010630BF11065E58200638
CP STORE RS210 0812BF11065F5820063C0812BF110660
CP STORE RS220 582006400812582006380912BD11065E
CP STORE RS230 477002315820063C0912BD11065F4770
...etc...
```

which I've confirmed does make CP happy.

Just wanted to let you know. &nbsp; `:)`

**Comment by s390guy** [comment]
Thanks.  I do not run VM myself, so I obviously honked that up without any testing.  Thank YOU for doing it for me.

I will fix it...

**Comment by Fish-Git** [comment]
### FYI:

Here's the fix:

```diff
--- satk-1/asma/asmbin.py	2015-11-03 17:07:58.888411300 -0800
+++ satk-0/asma/asmbin.py	2022-08-14 02:05:18.860655900 -0700
@@ -118,7 +118,7 @@
             chunks.extend(c.chunks(16))  # maximum of 16 bytes stored
         cmdfile=""
         for c in chunks:
-            cmdfile="%s%sSTORE R S %X %s\n" \
+            cmdfile="%s%sSTORE RS%X %s\n" \
                 % (cmdfile,cpcmd,c.addr,self.bytes_in_hex(c.data))
         #print("cmdfile:\n%s" % cmdfile)
         return cmdfile
```

Again, just trying to help!

**Comment by s390guy** [comment]
Committed correction for --vmc output format.  Thank you Fish.
