### ISSUE TITLE
length modifier exceeds allowed maximum of 256

### ISSUE THREAD

**Issue by Fish-Git** [s390guy/SATK#18]
```
FISHTEST CSECT
DSX      DS    XL512
DSC      DS    CL512
DCX      DC    XL512'0'
DCC      DC    CL512' '
         END
```

* [INSTRATE.list.txt](https://github.com/s390guy/SATK/files/7229090/INSTRATE.list.txt)

```
ASMA Ver. 0.2.1                                                                                     24 Sep 2021 20:17:40  Page     1

  LOC        OBJECT CODE       ADDR1     ADDR2    STMT

                              00000000  00000000     1 FISHTEST CSECT
                                                     2 DSX      DS    XL512
          ** [2] operand 1 length modifier exceeds allowed maximum of 256: 512
                                                     3 DSC      DS    CL512
          ** [3] operand 1 length modifier exceeds allowed maximum of 256: 512
                                                     4 DCX      DC    XL512'0'
          ** [4] operand 1 length modifier exceeds allowed maximum of 256: 512
                                                     5 DCC      DC    CL512' '
          ** [5] operand 1 length modifier exceeds allowed maximum of 256: 512
                                                     6          END
```

Since when are hex and char fields limited to just 256 bytes?!

I looked for such a documented limitation somewhere in the ASMA manual and could not find it anywhere. The only places that come anywhere close to mentioning such a limitation is:

Page 48:

> _**DC**_
> 
> _The optional length modifier [Ln] may be either an unsigned decimal self-defining term or an_
> _expression enclosed in parenthesis.  The value must not be less than one nor exceed the_
> _maximum allowed for the constant type and not excluded for the type._

Page 50:

> _**DS**_
> 
> _See the DC directive description of supported types and implied lengths and alignment._

And _**nowhere**_ is the "maximum allowed for the constant type" documented!

What the heck is going on Harold?!

**Comment by Fish-Git** [comment]
_**FYI:**_

* https://www.ibm.com/docs/en/zos/2.2.0?topic=SSLTBW_2.2.0/com.ibm.zos.v2r2.asma400/ds.htm

> _**DS instruction**_
>
> _The maximum length that can be specified for the character (C) and hexadecimal (X) type areas is 65,535 bytes rather than 256 bytes for the same DC operands._

**Comment by s390guy** [comment]
No idea why this is happening without examining the code.  Agree that whatever the maximum is it should be in the manual.

Will check out why this is happening/

**Comment by s390guy** [comment]
Committed change to increase maximum explicit length for C, CA, CE and X type constants to 65535.  Increase applies to both DS and DC constants.  Use of a length greater than 256 bytes in a storage-to-storage instruction will result in an error.

Documentation will be updated to reflect this change and previous omission of maximum length.

**Comment by Fish-Git** [comment]
Fixed! That was quick! Thank you!

Did not see any update to the ASMA manual regarding maximum length modifier value however. Should I presume that will be coming later? Or did you feel such a minor tweak wasn't warranted? If the latter, that's fine too! I'm just happy the problem itself was fixed!

Closing issue.
