### ISSUE TITLE
Sample programs PGM3 & PGM4 do not assemble because ARCHLVL follows ASAREA

### ISSUE THREAD

**Issue by srorso** [s390guy/SATK#20]
Commit 274c8dd changed macro ASAREA.mac to require a prior use of the ARCHLVL macro.  In both [PGM3](https://github.com/s390guy/SATK/tree/master/samples/guide/pgm3) and [PGM4](https://github.com/s390guy/SATK/tree/master/samples/guide/pgm4), ARCHLVL follows ASAREA, resulting in assembler diagnostics because the ASAREA macro does not expand. 

Changing the order of ASAREA and ARCHLVL addresses the issue in PGM3.  

Issue created for documentation only; no urgency.

**Comment by s390guy** [comment]
Thanks.  I will fix that and commit new assemblies and test runs to make sure PGM3 and PGM4 are still operational.

Nice to see you back playing with SATK :-).

**Comment by s390guy** [comment]
This issue has not been fixed for both PGM3 and PGM4.  All the tests have been rerun to reflect this change.

**Comment by s390guy** [comment]
Sorry, has NOW been fixed.  Also documentation in doc/Guide.odt and doc/Guide.pdf have both been updated to reflect the change is macro order.
