### ISSUE TITLE
TRAP64 generates 128-bit PSWs when assembled using -t s390x

### ISSUE THREAD

**Issue by srorso** [s390guy/SATK#22]
TRAP64 uses PSW directive to create PSWs for an ESA low core.  With -t S390x, default PSW format is z/Arch or 128-bit.  

A possible change would be to add code to test for Architecture Level 9 and override the default PSW with PSWE390 when encountered. 

Source and listing attached.  

[ztest-002.zip](https://github.com/s390guy/SATK/files/7699008/ztest-002.zip)

**Comment by s390guy** [comment]
Corrected TRAP64 PSW generation to inhibit creation of 128-bit PSW in some circumstances.  Updated documentation is SATK.odt and SATK.pdf to reflect this restriction.
