### ISSUE TITLE
(cosmetic) ASMA lines-per-page option

### ISSUE THREAD

**Issue by Fish-Git** [s390guy/SATK#23]
According to page 16 of the ASMA manual:

> Each page  consists of 55 lines, including the title line.

IMO this is too low of a value. There is too much wasted space at the bottom of each page IMO.

I happened to notice that IBM's HLASM defaults to 60 lines per page:

* https://www.ibm.com/docs/en/zos/2.1.0?topic=ao-linecount

which is the value I'm personally used to experiencing myself, even on the very old DOS/VS systems I used to work on more than 45 years ago.

It would be really nice if the `asma` command supported a new `--lpp` _(lines-per-page)_ command-line option, so the user could specify a value other than the current default of 55.

Just a thought. &nbsp; `:)`

Thanks.

**Comment by Fish-Git** [comment]
### FYI:

Here's how I have manually patched ASMA for myself in order to work around the problem:

```diff
--- satk-1/asma/asmlist.py	2020-07-27 14:13:04.894639600 -0700
+++ satk-0/asma/asmlist.py	2022-08-13 21:51:43.223613900 -0700
@@ -71,7 +71,7 @@
     addr_max={16:0xFFFF,24:0xFFFFFF,31:0x7FFFFFFF,64:0xFFFFFFFFFFFFFFFF}
     def __init__(self,asm):
         self.linesize=132
-        super().__init__(linesize=self.linesize,lines=55)
+        super().__init__(linesize=self.linesize,lines=59)
         self.asm=asm     # Access to the assembler for listing generation
 
         # Established by create() method when these structures actually exist
```

With the patch applied, my listings now look much better IMO: _(see e.g. starting at page 34 where the tables start, but it's evident in other places throughout the listing as well)_

* [**LPP-_55_**-bfp-001-divtoint.pdf](https://github.com/s390guy/SATK/files/9332721/LPP-55-bfp-001-divtoint.pdf)
* [**LPP-_59_**-bfp-001-divtoint.pdf](https://github.com/s390guy/SATK/files/9332723/LPP-59-bfp-001-divtoint.pdf)

It would be nice however if this could be controlled via a simple `--lpp nn` command line option instead of people having to manually patch ASMA for themselves.

Again, it's no big deal. &nbsp;It's just a thought _(wish/hope)._

**Comment by s390guy** [comment]
I will update ASMA to reflect your change.  Many of these things are "per ones taste".  I see you sent this back in Feb when I was so ill.  I do agree a command line option would be best.  For now, I will just update it per your request.

**Comment by Fish-Git** [comment]
Your recent commit (cd969b33b79ea813b4f4e8ab82558c9e84311dbf) appears to have fixed this problem! Thank you! Closing...
