### ISSUE TITLE
 Incorrect code generation with multiple USING statements

### ISSUE THREAD

**Issue by Fish-Git** [s390guy/SATK#25]
I have a program that I decided to add some additional helper function code to. I've added the new code to the very end of the program, past a bunch of existing tables which are quite large.

The _ORIGINAL_ code, which looked like this, works just fine:

```
FISHTEST START 0
STRTLABL EQU   *

R1       EQU   1
R15      EQU   15

         USING *,R15              (main base of program code)

START    DS    0H

*        ...
*        ...

         LAY   R1,FOOBAR
         MVI   0(R1),X'FF'

*        ...
*        ...

FOOBAR   EQU   STRTLABL+X'2000'

         DC    8192X'00'          (large tables...)

         END
```

The new updated version looks like this, which now crashes with an Addressing Exception:

```
FISHTEST START 0
STRTLABL EQU   *

R1       EQU   1
R12      EQU   12
R13      EQU   13
R15      EQU   15

         USING *,R15              (main base of program code)
         USING HELPERS,R12        (base of helper functions)

START    DS    0H

*        ...
*        ...

         LAY   R1,FOOBAR
         MVI   0(R1),X'FF'

*        ...
*        ...

         L     R12,AHELPERS
         BAS   R13,FUNC2

*        ...
*        ...

AHELPERS DC    A(HELPERS)

*        ...
*        ...

FOOBAR   EQU   STRTLABL+X'2000'

         DC    8192X'00'          (large tables...)



HELPERS  DS    0H                 (helper functions...)

FUNC1    DC    XL256'00'

FUNC2    DC    XL256'00'

         END
```

The reason why it is crashing is because the `LAY` instruction, due apparently to the introduction of the second USING statement, is now being generated incorrectly:

* [ORIGINAL-ASMATEST.pdf](https://github.com/s390guy/SATK/files/9356762/ORIGINAL-ASMATEST.pdf)
* [BADNEW-ASMATEST.pdf](https://github.com/s390guy/SATK/files/9356772/BADNEW-ASMATEST.pdf)

As you can see, in the original version, the `LAY` instruction was being generated as ` E310 F000 0271`, which is correct.

Now however, with the introduction of the second USING statement, it's being generated for reasons unknown as `E310 CFE8 FF71`, which is _very, **VERY**_ wrong, and is what is causing the Addressing Exception. (The displacement, for reasons unknown, is being incorrectly generated as a _negative_ value, thereby causing the `MVI` to crash with an Addressing Exception due to R1 now containing a very large address value that is _WAY_ past the end of available storage.)

I have not been able to find a workaround for this issue (other than to completely redesign/rewrite my program, which I am naturally extremely reluctant to do), so I'm dead in the water until you can get this fixed. (The above code is just a simple reproducible test case that illustrates the problem of course; the actual program, being a Hercules runtest instruction verification test program, is of course _much_ more complicated.)

Thanks.

**Comment by s390guy** [comment]
Fish, I see the issue.  Will look into it today.

**Comment by s390guy** [comment]
Reproduced your assembly.

**Comment by s390guy** [comment]
I have not figured out how to add documents as you did, so this part will be a little clunky.  Note this is supposed to look correct when posted.  At least that is how I read the info on quoting code.  I apologize if it does not.

```

ASMA Ver. 0.2.1                                                                                     17 Aug 2022 09:46:23  Page     1

      LOC            OBJECT CODE           ADDR1             ADDR2        STMT

                                      0000000000000000  0000000000002217     1 FISHTEST START 0
                                      0000000000000000  0000000000000001     2 STRTLABL EQU   *
                                                                             3
                                      0000000000000001  0000000000000001     4 R1       EQU   1
                                      000000000000000C  0000000000000001     5 R12      EQU   12
                                      000000000000000D  0000000000000001     6 R13      EQU   13
                                      000000000000000F  0000000000000001     7 R15      EQU   15
                                                                             8
0000000000000000                      0000000000000000                       9          USING *,R15              (main base of program code)
0000000000000000                      0000000000002018                      10          USING HELPERS,R12        (base of helper functions)
                                                                            11
0000000000000000                                                            12 START    DS    0H
                                                                            13
                                                                            14 *        ...
                                                                            15 *        ...
                                                                            16
0000000000000000  E310 CFE8 FF71                        0000000000002000    17          LAY   R1,FOOBAR
0000000000000006  92FF 1000                             0000000000000000    18          MVI   0(R1),X'FF'
                                                                            19
                                                                            20 *        ...
                                                                            21 *        ...
                                                                            22
000000000000000A  58C0 F014                             0000000000000014    23          L     R12,AHELPERS
000000000000000E  4DD0 C100                             0000000000002118    24          BAS   R13,FUNC2
                                                                            25
                                                                            26 *        ...
                                                                            27 *        ...
                                                                            28
0000000000000014  00002018                                                  29 AHELPERS DC    A(HELPERS)
                                                                            30
                                                                            31 *        ...
                                                                            32 *        ...
                                                                            33
                                      0000000000002000  0000000000000001    34 FOOBAR   EQU   STRTLABL+X'2000'
                                                                            35
0000000000000018  00000000 00000000                                         36          DC    8192X'00'          (large tables...)
                                                                            37
                                                                            38
                                                                            39
0000000000002018                                                            40 HELPERS  DS    0H                 (helper functions...)
                                                                            41
0000000000002018  00000000 00000000                                         42 FUNC1    DC    XL256'00'
                                                                            43
0000000000002118  00000000 00000000                                         44 FUNC2    DC    XL256'00'
                                                                            45
                                                                            46          END
ASMA Ver. 0.2.1                                                                                     17 Aug 2022 09:46:23  Page     2

     SYMBOL        TYPE  VALUE   LENGTH  DEFN  REFERENCES

AHELPERS            A    000014       4    29  23
FISHTEST            J    000000    8728     1
FOOBAR              U    002000       1    34  17
FUNC1               X    002018     256    42
FUNC2               X    002118     256    44  24
HELPERS             H    002018       2    40  10  29
IMAGE               1    000000    8728     0
R1                  U    000001       1     4  17  18
R12                 U    00000C       1     5  10  23
R13                 U    00000D       1     6  24
R15                 U    00000F       1     7   9
START               H    000000       2    12
STRTLABL            U    000000       1     2  34
ASMA Ver. 0.2.1                                                                                     17 Aug 2022 09:46:23  Page     3

MACRO   DEFN  REFERENCES

No defined macros
ASMA Ver. 0.2.1                                                                                     17 Aug 2022 09:46:23  Page     4

   DESC     SYMBOL   SIZE     POS        ADDR

Entry: 0

Image      IMAGE     8728  0000-2217  0000-2217
  Region             8728  0000-2217  0000-2217
    CSECT  FISHTEST  8728  0000-2217  0000-2217

```
This is the assembly listing from ASMA for your test code.  The troublesome statement 17 shows up just as in your listing.

The LAY creates the following base/displacement fields:
   Base: C (Register 12)
  Disp L2 - FE8
  DIsp H2 - FF

The combined signed displacement is FFFE8, or -X'18'.

The base using register 12 is HELPERS.  HELPERS has a value of:
HELPERS             H    002018       2    40  10  29

The label for which a displacement is being created is FOOBAR.  FOOBAR is:

FOOBAR              U    002000       1    34  17

The label for which the instruction requires a displacement is less than the actual declared base of HELPERS.

This is perfectly legitimate for instructions with 20 bit displacements.  See the latest PoO on 7-269 in the LOAD ADDRESS discussion.

ASMA calculates the displacement as:

FOOBAR-HELPERS or a displacement of -X'18'

Obviously, this code while it assembles correctly, will not execute because register 12 likely (at least in the test case) contains 0.

The crux of the matter is the two overlapping bases: 15 and 12.  While unstated, I suspect register 15 was expected to be the base of statement 17 and not register 12.  When this situation arises ASMA will select the base register that has the shortest displacement.  In this case register 12 because a negative displacement is always shorter than a positive displacement.

The solution to this problem is to move the USING for register 12 in statement 10 to the statement following the 
L 12,AHELPERS where register 12 is actually initialized with the correct address.

With this change you get R15 as the base register in statement 17 and the following BAS is assembled using register 12.

While the construct of the original code may work with some proprietary assemblers of more recent vintage, it will not with ASMA.   The placement of the USING R12 early in the assembly has the effect of communicating to ASMA something that is not in fact real.  R12 **at that point** does NOT contain the expected base value.

And ASMA is working as designed.  (I have not really found a better algorithm for selecting between two overlapping valid base registers.)

I hope that does not mess up anything else in your much larger program even though it fixes the test case.

I will leave this issue open for your response.

Harold Grovesteen

**Comment by Fish-Git** [comment]
### FYI:
> I have not figured out how to add documents as you did...

You obviously missed _(as many people do, myself included when I first discovered it long ago)_ the helpful informational message that GitHub displays at the bottom of its message/comment box that you type your reply into:

> _Attach files by dragging & dropping, selecting or pasting them._

So simply drag the file from your desktop and drop it into the GitHub message/comment box!

**PLEASE NOTE** however, that **[GitHub only supports certain file extensions](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)** (and has file size limits as well), so if it's a file with a file extension that GitHub doesn't support, just .zip it and then post the .zip file.

They also support "markdown" formatting too, allowing one to format their comments to be a bit more readable. I use it all the time. Just do a search for "github markdown" and you'll find all kinds of helpful pages on the subject:

* **[Basic writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)**
* **[Wikipedia article on "Markdown"](https://en.wikipedia.org/wiki/Markdown)**

Here's a helpful cheat sheet that I found somewhere but I can't seem to find anymore:

* [**GitHub Flavored Markdown Cheat Sheet PDF file**](https://github.com/s390guy/SATK/files/9365981/GitHub.Flavored.Markdown.pdf)
 
Hope that helps!

**Comment by Fish-Git** [comment]
> When this situation arises ASMA will select the base register that has the shortest displacement.

I'm not sure I agree with that logic. If it were me, I would select the register specified in the first still-active USING which provides addressability to the target in question. Or put another way, the one who's address comes first.

`USING *,R15` provides addressability starting at address X'0000', whereas `USING HELPERS,R12` provides addressability starting at address X'2018'. Thus R15 should have been used IMHO. The only time R12 should be used while R15 is still active (hasn't been `DROP`ped) would _only_ be (again, IMHO) if/when R15 _couldn't_ be used (because doing so would cause an addressability error).

> And ASMA is working as designed.

ASMA is certainly free to do things however it wants, and does not have to match the behavior of any other assembler(s) out there. I accept that.

But that doesn't mean I have to _like_ it! &nbsp; `;-)`

> (I have not really found a better algorithm for selecting between two overlapping valid base registers.)

What about my idea stated above?

> I hope that does not mess up anything else in your much larger program even though it fixes the test case.

Funny you should mention that. &nbsp; `:)`

As it turns out, after having reviewed the program more closely, it ironically turns out that the code in question was completely bogus anyway and wasn't needed at all. So I was able to resolve my problem by simply removing the bogus/unneeded instructions completely. It now builds and runs just fine, so I must apologize for marking this issue as "HOT!". As it turns out it wasn't urgent at all and I was able to easily work around the issue. 

Of course, I didn't _know_ that at the time. I only discovered it much later (just today as a matter of fact) after having examined the program in question more closely to see what it was trying to do and why.

So my apologies for screaming "Fire!" (or "The sky is falling!") &nbsp; It was a most unnecessary knee jerk reaction and I should have known better. Please accept my apology.

> I will leave this issue open for your response.

Thanks. I really appreciate the quick, detailed explanation of what was actually going on. You can close this issue now if you want.

But I'd really appreciate you at least _considering_ my suggested handling of the situation. I have no idea whether that's how other assembler(s) deal with the situation or not (but I think I may give it a try if only to satisfy my own curiosity), but ASMA's current behavior in such situations just seems to be IMHO (and forgive me for saying so), _**wrong/illogical**_.

Thanks for everything you do, Harold. You're a nice guy and I _really_ appreciate all of your hard work.

Take care my friend!

**Comment by s390guy** [comment]
This behavior is not ASMA specific.

In the most recent assembler manual I have, HLASM V1 R6 Language Reference Manual, page 221, says:

> When two ranges overlap, the assembler computes displacements from the base address that gives the smallest non-negative displacement; or if no non-negative displacement can be found, for long displacement instructions, the base register giving the smallest negative displacement; it uses the corresponding base register when it assembles within the range overlap.  This applies only to implicit addresses that appear after the second USING instruction.

ASMA does not have quite the number and flavors of USING that HLASM supports, but I spent a lot of time trying to make base register selection compatible with other assemblers.

I agree.  You don't have to like it.  :-).  And ASMA does have some quirks. It was never designed as a direct replacement, but as a tool external to any mainframe operating system allowing development of relatively complex code targeting a bare-metal environment.  As I know you know.

But in this case it is not just ASMA that seems to you "wrong/illogical".

Harold

**Comment by s390guy** [comment]
Something else you or others may find of use since we are on the topic of base registers...

When ASMA needs to create a base/displacement pair of values for insertion into an instruction's fields, it is the instruction which dictates the scope of the using.  If the instruction contains a 12-bit displacement, the range is base+0 through base+4095.  If the instruction has a 20-bit displacement, the range is base-524288 to base+524287.

In a case where the displacement will not fit within the instruction's displacement field(s), the base register is rejected as a possible candidate for the instruction.

Harold

**Comment by Fish-Git** [comment]
> This behavior is not ASMA specific.

I respectfully disagree.

The text you quoted describes behavior that is _not_ the same as ASMA's.

Previously, you wrote:

> > When this situation arises ASMA will select the base register that has the shortest displacement. In this case register 12 because a negative displacement is always shorter than a positive displacement.

But based on your quoted HLASM behavior (and confirmed further below by myself):

> > When two ranges overlap, the assembler computes displacements from the base address that gives the smallest _**non-negative**_ displacement; _**or** if no non-negative displacement can be found,_ for long displacement instructions, the base register giving the _smallest negative displacement;_ it uses the corresponding base register when it assembles within the range overlap. This applies only to implicit addresses that appear after the second USING instruction.

ASMA is using the smallest displacement _period_, with negative displacements always wining over any non-negative displacement. HLASM on the other hand, always chooses (prefers) _non-negative_ displacements over any negative one, and only falls back to using a negative displacement only when it has no other choice (i.e. only when there aren't any non-negative displacements).

ASMA's behavior appears to be ASMA-specific, and does _not_ match HLASM's. Refer to the below attached printouts that, via my new slightly modified test, illustrates the issue quite clearly:

* [**ASMATEST.pdf**](https://github.com/s390guy/SATK/files/9375977/ASMATEST.pdf)
* [**HLASM.pdf**](https://github.com/s390guy/SATK/files/9375997/S0W1.IBMUSER.FISH.FISHASMH.JOB00211.2022-08-18.10.34.37.pdf)

_(and just in case you want to see the JCL I used):_

* [HLASM (JCL).pdf](https://github.com/s390guy/SATK/files/9375988/S0W1.IBMUSER.FISH.FISHASMH.JOB00211.2022-08-18.10.36.02.pdf)

As you can plainly see, HLASM is choosing correctly. ASMA is not.

Respectfully submitted.

If I get a chance I might try locating the code that deals with that and try hacking some sort of fix for you, but I don't really know PHP, so I'm very hopeful I'll be able to pull it off.

**Comment by s390guy** [comment]
Thanks for adding the additional statement in HLASM.  What did not jump out at me is that HLASM gives preference to all non-negative displacements.  This I did not recognize until you added the emphasis.  And yes, that is not what ASMA is doing.

The Python (not PHP) code that selects the base register is tied to how Python does sorting.  I would need to look at that and see how it might be adjusted to get these results.

**Comment by Fish-Git** [comment]
> ... Python (not PHP) ...

_(Oops!)_ Sorry. My bad. Result of my own ignorance and sloppy writing. Won't happen again.

**Comment by Fish-Git** [comment]
Your latest commit (da1bec1b37ad2e48095d096a979ee58e5166195c) appears to have fixed the problem! Thank you! Closing...
