### ISSUE TITLE
ORG statement without operands is rejected

### ISSUE THREAD

**Issue by srorso** [s390guy/SATK#28]
In a DSECT or a CSECT, an ORG statement without an operand, or "ORG ," to signify a null operand to allow an inline commend, is rejected.  This behavior is handiest in DSECTS with multiple overlays, to allow the DSECT location counter to be returned to the highest location previously assigned plus one.  I have included a test case that illustrates a reasonable use in a DSECT and a ridiculous but but still illustrative use in a CSECT.  

HLASM and older assemblers allowed this, and when encountered, the location counter was set to the highest location to be next assigned in the CSECT or DSECT.  This is documented in the HLASM Language Reference, SC26-4940-07 (July 2015) on pages 185-187 (includes examples).  

A partial workaround is available by using an EQU to tag each "highest" location assigned and manually keeping track of which symbol so defined is currently the highest.  So no urgency.  

If this is outside the scope of ASMA, which quite reasonably does not promise absolute fidelity to every assembler ever written for an IBM mainframe, a documentation update might be in order.  

[ztest-998.zip](https://github.com/s390guy/SATK/files/9739328/ztest-998.zip)

**Comment by s390guy** [comment]
Yup.  ASMA does not like it.  I actually thought this was supported.  I have not really needed it, so got to find the crack it decided to fall into.

**Comment by s390guy** [comment]
Committed enhancement to allow an optional operand on the ORG statement.  When the operand is omitted it sets the location counter to the end of the current active section.  doc/asma/ASMA.odt and dos/asma/ASMA.pdf were updated to reflect this enhancement.  Previously the documentation stated that the operand was required.

I will close this Steve after you have indicated ORG is now working as expected.

**Comment by srorso** [comment]
I guess I need to change two things in this issue: 1) this is an enhancement (thanks) and 2) the doc change would need to be along the lines of getting me to read the words on the page (my apologies).  Oh well....

That said, many thanks!  The enhancement works wonderfully and the updated documentation now reflects what I _thought_ I read before.

**Comment by s390guy** [comment]
With your concurrence that ORG is _now_ working as it should, I will close this issue.  

With each of these enhancements (or bug fixes depending upon the person's view) someone finds ASMA to be more "usable".  The doc tries to reflect ASMA's current state.  If it doesn't that is its own "bug".  Individuals have their own coding style that differs from my own.  Starting out, ASMA was influenced by my personal coding style and so some things I do not use took a lower priority.  Read "missed the cut".  And while I do not really enjoy people finding such issues, SATK gets better as each ends up being addressed.  The more that someone can sit down and accomplish their goals without "hiccups" or adjustments that do not feel natural to them the better.

Can not do anything about improving reading the page in the doc.  But, you are not alone if that makes you feel any better.
