### ISSUE TITLE
sopl.SOPLError: [2218]-1 could not open for reading file: zem-insn.msl

### ISSUE THREAD

**Issue by Fish-Git** [s390guy/SATK#29]
With the latest commit (96ff33d54f7da40d50de70795ee2ef18502675f0), I am now unable to build anything. No matter what I try to build, it always results in:

<pre>
Solution Build begun at 10/14/2022 6:30:53 PM
SVN: 5868-modified

1>------ Rebuild All started: Project: ASMATEST, Configuration: Debug Win32 ------
1>Performing Makefile project actions
1>asma.py Copyright (C) 2014-2020 Harold Grovesteen
1>Traceback (most recent call last):
1>  File "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_Git\_Harold\SATK-0\tools\asma.py", line 419, in <module>
1>    ASMA(tool,dm).run()
1>  File "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_Git\_Harold\SATK-0\tools\asma.py", line 104, in __init__
1>    maclib=args["maclib"])
1>  File "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_Git\_Harold\SATK-0\asma\assembler.py", line 887, in __init__
1>    self.OMF=asmoper.OperMgr(self,machine,msl,mslpath)
1>  File "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_Git\_Harold\SATK-0\asma\asmoper.py", line 140, in __init__
1>    self.cache=self.__getMachine(machine,msl,mslpath=mslpath,debug=debug)
1>  File "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_Git\_Harold\SATK-0\asma\asmoper.py", line 162, in __getMachine
1>    mslproc.build(mslfile,fail=True)
1>  File "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_Git\_Harold\SATK-0\asma\msldb.py", line 1562, in build
1>    self.recognize(filename,fail=fail,debug=debug)
1>  File "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_Git\_Harold\SATK-0\tools/lang\sopl.py", line 511, in recognize
1>    self.__readfile(filename,line=None)
1>  File "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_Git\_Harold\SATK-0\tools/lang\sopl.py", line 380, in __readfile
1>    self.__do_include(source,stmt)
1>  File "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_Git\_Harold\SATK-0\tools/lang\sopl.py", line 276, in __do_include
1>    self.__readfile(parts[1],line=source)
<b>1>  File "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_Git\_Harold\SATK-0\tools/lang\sopl.py", line 325, in __readfile
1>    msg="could not open for reading file: %s" % filename)
1>  File "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_Git\_Harold\SATK-0\tools/lang\sopl.py", line 426, in _do_error
1>    raise e from None
1>sopl.SOPLError: [2218]-1 could not open for reading file: zem-insn.msl</b>
1>Project : error PRJ0002 : Error result 1 returned from 'C:\Windows\SysWow64\cmd.exe'.
1>Build Time 0:00
1>Build log was saved at "file://c:\Users\Fish\Documents\Visual Studio 2008\Projects\MyProjects\ASMA-0\ASMATEST\BuildLog.htm"
1>ASMATEST - 1 error(s), 0 warning(s)

1>ASMATEST - 1 error(s), 0 warning(s)

Solution Build ended at 10/14/2022 6:30:54 PM
Solution Build duration 00:00:01
</pre>

**Comment by s390guy** [comment]
Sorry about that!!! Missed committing the new MSL file containing the new extended mnemonic definitions.  Committed the missing file.  You should be able to go to the latest commit and it should work.

I will leave the issue open until the correction is confirmed.

My apologies Fish.  Mea Culpa.

**Comment by Fish-Git** [comment]
> Missed committing the new MSL file containing the new extended mnemonic definitions.

I figured as much. &nbsp;`:)`

> Committed the missing file. You should be able to go to the latest commit and it should work.
> 
> I will leave the issue open until the correction is confirmed.

Fix confirmed. &nbsp;Closing issue. &nbsp;Thanks, Harold.

> My apologies Fish. Mea Culpa.

No need to apologize! &nbsp;I've done _far_ worse! &nbsp;`;-)`
