### ISSUE TITLE
error   : [66:16] undefined label: QWORD

### ISSUE THREAD

**Issue by Fish-Git** [s390guy/SATK#32]
### _(Edited)_

If I do:
```
         VL    V0,=(16)X'11'        This works okay
         VL    V0,=(QWORD)X'11'     This gets an ERROR

FOO      DC    (16)X'11'            This works okay
BAR      DC    (QWORD)X'11'         This gets an ERROR

QWORD    EQU   16               Size of a quad-word vector register
```

It fails with:

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ** [66:16] undefined label: QWORD

&nbsp;
But if I do this: &nbsp;_(define QWORD up front)_

```
QWORD    EQU   16               Size of a quad-word vector register

         VL    V0,=(16)X'11'        This works okay
         VL    V0,=(QWORD)X'11'     This now works okay too!

FOO      DC    (16)X'11'            This works okay
BAR      DC    (QWORD)X'11'         This now works okay too!
```

It works fine!

Why?

**Comment by s390guy** [comment]
This is a Pass 1 vs. Pass 2 issue.  QWORD is being used to define the duplication factor for the X constant.  During Pass 1 all labels used to define a storage allocation must be defined before being used because storage allocations occur in Pass 1.  Hence moving the EQU to the front allows it to be defined before reference in Pass 1.  Otherwise, in Pass1, the QWORD label at the end is yet to be defined when its use is required for evaluation of the duplication factor and results in "undefined label".

**Comment by Fish-Git** [comment]
> During Pass 1 all labels used to define a storage allocation must be defined before being used because storage allocations occur in Pass 1.

I see.

I always thought the purpose of Pass 1 was simply to _gather_ (and save) all of the information that Pass 2 might need (such as the defined values of EQUs, etc), so that Pass 2 could then do the actual assembly (i.e. code generation) completely unimpeded.

I guess I was wrong. &nbsp;`:(`

Anyway, it's no big deal. It's easy enough to define my equates up front at the beginning of my program. I'm just used to having the code always come first, followed by all the equates and DSECTS and working storage, etc. It just seems somewhat out of the ordinary to have to do such stuff _(or rather one small part of such stuff)_ at the beginning of the program before the code (the actual program itself) is defined.

But as I said it's no big deal. I appreciate the explanation Harold. Thanks. Closing issue.

_(Do you have any "Labels" defined for your GitHub Issues? If you do, assign this issue as "Question", not "Bug". Thanks.)_

**Comment by s390guy** [comment]
What you are used to is available with modern proprietary mainframe assemblers.  Those are multi-pass.  ASMA is two-pass.  The multi-pass assembler will continue passes until no knew labels are defined and then in the final pass generate the storage content (and error messages).  Sounds simple, but ends up being very complex internally.

I spent a great deal of effort looking into to making ASMA multi-pass.  Internally that is a very complex change.

**Comment by Fish-Git** [comment]
> What you are used to is available with modern proprietary mainframe assemblers. Those are multi-pass. The multi-pass assembler will continue passes until no knew labels are defined and then in the final pass generate the storage content (and error messages).

Yep. You're right. That is what I'm used to.

> Sounds simple, but ends up being very complex internally.

I don't doubt it!

> ASMA is two-pass.

Understood.

> I spent a great deal of effort looking into to making ASMA multi-pass. Internally that is a very complex change.

10-4. To be clear, I'm _**not**_ asking you to make ASMA into a multi-pass assembler. I'm not! And I'm not _complaining_ about ASMA's behavior regarding this issue either. I promise you!

I was just wondering _why_ it was happening due to the way I thought ASMA worked. And you've explained that. So I'm happy now. As I said, it's such a little thing and I can _easily_ deal with it, so _PLEASE_, let's not talk about this any longer. Okay? ASMA is a _great_ product, and I'm a _VERY_ happy customer!

But then you already knew that. &nbsp;`:)`
