### ISSUE TITLE
Vector opcodes

### ISSUE THREAD

**Issue by salva-rczero** [s390guy/SATK#33]
Hi @s390guy,

I can't assemble some vector opcodes: 

- [x]  VLEB
- [x]  VLEH
- [ ]  VLEF: ** [3495] @[78]-1 macro definition for VLEF not found in MACLIB path as VLEF.mac
- [ ]  VLEG:  ** [3497] @[80]-1 macro definition for VLEG not found in MACLIB path as VLEG.mac
- [x]  VL
- [ ]  VLBB: ** [3512] @[95]-1 macro definition for VLBB not found in MACLIB path as VLBB.mac
- [x]  LCBB
- [x]  VST
- [x]  VLM
- [x]  VSTM
- [x]  VGBM
- [x]  VN

I can find them in msl files, but no in PoO.txt. 

But, really, I have no idea what I am doing, can you clarify if they are really not supported or am I doing something wrong? In which case, can you guide me on how to extend SATK?

Thank you very much, without SATK my progress would be even slower.

**Comment by s390guy** [comment]
These instruction _are_ in the PoO.txt file in this repository:
asma/msl/PoO.txt 

This suggests the version of SATK you are using predates when these instructions were added.  I would suggest downloading a new version or doing a pull from the repository.

**Comment by s390guy** [comment]
BTW, Welcome to using SATK!  You will learn to like working with it once you become familiar.  There is nothing like it for bare-metal programming of mainframes outside of a mainframe.

**Comment by salva-rczero** [comment]
Thanks you @s390guy , It's working fine. I could have sworn I had updated, but I was a "git pull" behind.
