### ISSUE TITLE
Iplasma.py rejects comments in a List Directed IPL file as invalid

### ISSUE THREAD

**Issue by srorso** [s390guy/SATK#34]
Comments have an asterisk in the first position; other systems ignore comments when reading List Directed IPL files.  

Workaround: remove the comment line.  

Very low impact.

**Comment by s390guy** [comment]
iplasma.py accepted comments starting with a # but not an *.  Corrected user reported error by adding support for comments starting with either a # or *.  Comments may also be supplied in the control file following an image file name and load address with either a # or *.

Fixed.
