### ISSUE TITLE
Literal operand 2 invalid: expected another value signaled by a comma

### ISSUE THREAD

**Issue by Fish-Git** [s390guy/SATK#37]
@s390guy 

### Input:

<pre>
FISHTEST START 0
         USING *,R0
         ORG   FISHTEST+X'8E'
PGMCODE  DC    XL2'0000'
         ORG   FISHTEST+X'200'
         CLC   PGMCODE,=X'0008'
<b>         L     R2,=F'007F0A72'
         CL    R2,=F'7F0A7200'
         L     R2,=F'007F0A72'
         CL    R2,=F'FE14E400'</b>
         LTORG ,
R0       EQU   0
R2       EQU   2
         END
</pre>

### Output:

<pre>
ASMA Ver. 0.7.0                                                                                     18 Mar 2024 16:16:28  Page     1

  LOC        OBJECT CODE       ADDR1     ADDR2    STMT

                              00000000  00000207     1 FISHTEST START 0
00000000                      00000000               2          USING *,R0
00000000                      00000000  0000008E     3          ORG   FISHTEST+X'8E'
0000008E  0000                                       4 PGMCODE  DC    XL2'0000'
00000090                      00000090  00000200     5          ORG   FISHTEST+X'200'
00000200  D501 008E 0206      0000008E  00000206     6          CLC   PGMCODE,=X'0008'
                                                     <b>7          L     R2,=F'007F0A72'
          ** [7] literal operand 2 invalid: expected another value signaled by a comma, found "F0A72'"
                                                     8          CL    R2,=F'7F0A7200'
          ** [8] literal operand 2 invalid: expected another value signaled by a comma, found "F0A7200'"
                                                     9          L     R2,=F'007F0A72'
          ** [9] literal operand 2 invalid: expected another value signaled by a comma, found "F0A72'"
                                                    10          CL    R2,=F'FE14E400'
          ** [10] literal operand 2 invalid: expected fixed point nominal value, found "FE14E400'"</b>
00000206                                            11          LTORG ,
00000206  0008                                      12                =X'0008'
                              00000000  00000001    13 R0       EQU   0
                              00000002  00000001    14 R2       EQU   2
                                                    15          END
ASMA Ver. 0.7.0                                                                                     18 Mar 2024 16:16:28  Page     2

     SYMBOL        TYPE  VALUE   LENGTH  DEFN  REFERENCES

FISHTEST            J    000000     520     1   3   5
IMAGE               1    000000     520     0
PGMCODE             X    00008E       2     4   6
R0                  U    000000       1    13   2
R2                  U    000002       1    14
=X'0008'            X    000206       2    12   6
ASMA Ver. 0.7.0                                                                                     18 Mar 2024 16:16:28  Page     3

MACRO  DEFN  REFERENCES

No defined macros
ASMA Ver. 0.7.0                                                                                     18 Mar 2024 16:16:28  Page     4

   DESC     SYMBOL   SIZE    POS      ADDR

Entry: 0

Image      IMAGE      520  000-207  000-207
  Region              520  000-207  000-207
    CSECT  FISHTEST   520  000-207  000-207
ASMA Ver. 0.7.0                                                                                     18 Mar 2024 16:16:28  Page     5

   STMT                                           FILE NAME

1     C:\Users\Fish\Documents\Visual Studio 2008\Projects\MyProjects\ASMA-0\ASMATEST\ASMATEST.asm

** ERRORS FOUND: 4 **

<b>[7] literal operand 2 invalid: expected another value signaled by a comma, found "F0A72'"
[8] literal operand 2 invalid: expected another value signaled by a comma, found "F0A7200'"
[9] literal operand 2 invalid: expected another value signaled by a comma, found "F0A72'"
[10] literal operand 2 invalid: expected fixed point nominal value, found "FE14E400'"</b>
</pre>

**Comment by Fish-Git** [comment]
# (DOH!!)

### PEBKAC!

Harold, I apologize _profusely!_ &nbsp;The penny finally dropped!

I can't believe it took me this long (two freaking days!) to finally realize that ASMA is indeed working correctly, and that my test program is indeed _**VERY WRONG!**_

My programmer brain looked at `=F'007F0A72'` and actually thought "That's a valid fullword constant! That's a whole number! There's nothing syntactically wrong with that! What's going on?!"

But it's not!

It's _not_ a valid whole number!

It's a _**HEXA-**_ decimal numberl! &nbsp;_(DOH!)_

_(me: smacks forehead)_

=F'65535' is a valid fullword constant.
=F'FFFF' is not. &nbsp;(duh)

I'm starting to get scared. My brain must be getting old. I would never have made such an amateurish mistake years ago.

I also failed to test the same program using a different assembler too. I arrogantly believed "There's no need to test/verify that! I know I'm right! Testing/verifying it would just be a waste of time."

After the penny dropped and I realized I was wrong _(only just this morning!)_, I took the time to try the same thing on DOS/VS _(faster and easier for me than bringing up z/OS)_ and sure enough, it too complained with almost the exact same error messages as ASMA's:
```
  STMNT ERROR NO.  MESSAGE
 
     7   IPK112    INVALID CHARACTER IN CONSTANT, 'F0A72''
     8   IPK112    INVALID CHARACTER IN CONSTANT, 'F0A7200''
     9   IPK112    INVALID CHARACTER IN CONSTANT, 'F0A72''
    10   IPK112    INVALID CHARACTER IN CONSTANT, 'FE14E400'
```


&nbsp;_(me: smacks self upside the head a few more times for my arrogance/laziness -- HARD!)_


So please forgive me. I was just being stupid. Call it a brain fart. Call it arrogance. Call it anything you want. But I was obviously wrong and ASMA was _(i.e. you were)_ obviously right.

I'm sorry. Truly. &nbsp;`:-(`

I am closing this issue as an obvious PEBKAC on my part.

Feel free to even delete it completely if you want.

I'm going to go crawl back to my den now and lick my wounds.

**Comment by wrljet** [comment]
> I'm going to go crawl back to my den now and lick my wounds.

🙂

**Comment by s390guy** [comment]
Updated ASMA.odt and ASMA.pdf on page 50 to be explicit that DECIMAL values are required for D, F, FD, and H constant types.
