### ISSUE TITLE
VCVB and VCVBG:

### ISSUE THREAD

**Issue by JamesWekel** [s390guy/SATK#38]
From the z/Architecture Principles of Operation, SA22-7832-13 page 25-8; the VECTOR CONVERT TO BINARY instructions 
```
    VCVB R1,V2,M3[,M4]
    VCVBG R1,V2,M3[,M4]
```
have an option M4 field. Using SATK 0.7.0 with an M4 field, I receive the following error: 
```
                                                535+         VCVB  R1,V1,1,8           test instruction
          ** [535] 4 operands exceeds the number allowed for the operation, 3

                                                   562+         VCVBG R1,V1,1,8           test instruction
          ** [562] 4 operands exceeds the number allowed for the operation, 3
```

Thanks for the tool kit!!

Jim

**Comment by s390guy** [comment]
With the -12 version of the PoO, these two instructions had another mask field added.  The format change was missed.  The latest commit changed the instruction format in the related MSL files.  Closing this report.

**Comment by s390guy** [comment]
James, please send me a message at h.grovsteen@tx.rr.com or post to satk@groups.io.  Curious about your project with SATK.

Just do a pull from the SATK repository to get the correction.
