### ISSUE TITLE
Missing  "Getting started"

### ISSUE THREAD

**Issue by BertLindeman** [s390guy/SATK#7]
Hi Harold,

This is a fun area you opened here. 
I got this far:
- downloaded zip from github
- unzipped (in my case today on a windows pc)
- read the introduction, README, README.SAMPLES.txt
- verified that my python is at least 3.3
- have seen hercules conf and rc files (and have some hercules versions ;-) )

So I am at a stage: **now what**.
Would like to assemble a hello world program and run it.
But I do not want to override anything in the distribution.
Have seen many references in SATK to "only a hello world program"

So question like:
- Do I need to set any path or other environment?

Suggestions (just typing out loud..)?:
- first start hercules and load and run sample xx
- create a directory `mysrc` to keep your own creations ( or better advice? subdir of `src`?)
- use a copy of ???? 
- etc...

Willing to help write a "Getting started"

**Comment by Fish-Git** [comment]
FWIW to anyone reading this, I have been using Harold's fantastic SATK/ASMA product for a couple of years now and it _totally rocks!_

I have used it to write _many_ stand-alone test cases for the Hercules project and it has proven itself to be absolutely _invaluable!_

Well done and _**THANK YOU**_, Harold! &nbsp; `:)`

**Comment by s390guy** [comment]
This was added to the ASMA.odt / ASMA.pdf document
